### PR TITLE
Legend bar

### PR DESCRIPTION
**Pull request by zmalkmus**
Added a legend for the dynamic simulation. It now changes values based on the current state (v angle, v magnitude, and frequency).

Also cleaned up changed files and removed a redundant index.html file.

Default view
image

V Angle (min: -0.80, max: 0.2)
image

V Magnitude (min: -3.555 max: 3.01)
image

Frequency (min:0.9999 max: 1.0002)
image

Ability to be dragged
image

### CODE REVIEW

**Comment by jinningwang** [comment]
Well done! Some minor comments:

1. In the future, newly developed features might be merged into ``develop`` branch first, and we'll do the regular merge from ``branch`` to ``master`` regularly. In this way, we can have a better release manner.
2. Would you mind putting a full screenshot here? So I can make sure the overall layout is okay.
3. Are the range for the legend bar consistent with user settings?

**Comment by zmalkmus** [comment]
Jinning,

Ah, I was confused what the develop branch was for. I will do this in the
future.

Here is the full view of the placement of the legend.
[image: image.png]

As for the value ranges, thank you for catching this. I had mentally
skipped over the possibility and assumed the values were static. Just to
make sure I didn't miss anything, the range should correspond to the
frequency min and max values in the configuration panel?

I apologize for the mistake.

Thank you,
Zack

**Comment by jinningwang** [comment]
> Jinning, Ah, I was confused what the develop branch was for. I will do this in the future.

My practice would be to merge "patch" version ``feature1`` -> develop, ``feature2`` -> ``develop``, etc.
After accumulating several patch versions, summarize them as a minor version, and do``develop`` -> ``master``. This is because some bugs or defects can be detected when using ``develop``.
More details about versioning can be found at [Semantic Versioning 2.0.0](https://semver.org/).

> Here is the full view of the placement of the legend. [image: image.png] 
It didn't load the actual page but the file name here.

> As for the value ranges, thank you for catching this. I had mentally skipped over the possibility and assumed the values were static. Just to make sure I didn't miss anything, the range should correspond to the frequency min and max values in the configuration panel? I apologize for the mistake.
It's fine. Check the documentation about the customized value range, Nicholas should have mentioned this in the updated documentation.
We would expect the legend bar to be consistent with the user-input value range, so I feel this might need some more effort.

BTW, in the dynamic simulation, we have bus voltage, bus frequency, and bus angle. We might need to change the legend name accordingly if change the displayed variable.

**Comment by zmalkmus** [comment]
> It didn't load the actual page but the file name here.

The image did not transfer correctly through email unfortunately. I have corrected the original image to show the full view.

> > As for the value ranges, thank you for catching this. I had mentally skipped over the possibility and assumed the values were static. Just to make sure I didn't miss anything, the range should correspond to the frequency min and max values in the configuration panel? I apologize for the mistake.
> > It's fine. Check the documentation about the customized value range, Nicholas should have mentioned this in the updated documentation.
> > We would expect the legend bar to be consistent with the user-input value range, so I feel this might need some more effort.
> 
> BTW, in the dynamic simulation, we have bus voltage, bus frequency, and bus angle. We might need to change the legend name accordingly if change the displayed variable.

I will make some event handlers to change the title and values as they get updated through use of the application. I will continue to work on this.

I appreciate your feedback.

**Pull request merged**
